/** Every string the site shows. Protocol names stay as VLESS, TCP, WS, gRPC, Reality. */

export const RAW_KEYS = [
  'parse_error',
  'invalid_field',
  'tcp_refused',
  'timeout',
  'tls_fail',
  'reality_fail',
  'handshake_fail',
  'http_fail',
  'no_data',
  'exit_ip_leak',
  'dead',
  'working',
  'unstable',
  'xray-http',
] as const

export type RawKey = (typeof RAW_KEYS)[number]

const reasons = {
  parse_error: 'Ссылка не разобралась',
  invalid_field: 'Ошибка в поле',
  tcp_refused: 'Сервер отклонил подключение',
  timeout: 'Нет ответа',
  tls_fail: 'Ошибка TLS',
  reality_fail: 'Ошибка Reality',
  handshake_fail: 'Не удалось подключиться',
  http_fail: 'Сайт не открылся',
  no_data: 'Подключается, но не передаёт данные',
  exit_ip_leak: 'Трафик идёт мимо прокси',
  dead: 'Не работает',
} as const

const statuses = {
  working: 'Рабочий',
  unstable: 'Нестабильный',
  dead: 'Не работает',
} as const

const probes = {
  'xray-http': 'Проверка через прокси',
} as const

export const ru = {
  brand: 'V2Hub',
  loading: 'Загружаем список…',
  noData: 'Нет данных',
  retry: 'Повторить',
  loadFailed: 'Не удалось загрузить данные',
  dataBroken: 'Файл данных повреждён',
  refreshFailed: 'Не удалось обновить',
  alreadyFresh: 'Уже актуально',
  refreshed: 'Обновлено',
  refreshedNew: (count: number) => `Обновлено · +${count} новых`,
  updateAvailable: 'Есть обновление',
  refresh: 'Обновить',
  themeDark: 'Тёмная тема',
  themeLight: 'Светлая тема',
  close: 'Закрыть',
  copyFailed: 'Не удалось скопировать',
  copied: 'Скопировано',
  linkCopied: 'Ссылка скопирована',
  nothingFound: 'Ничего не найдено.',
  noProxies: 'Проверенных прокси нет.',
  tabs: {
    configs: 'Конфиги',
    telegram: 'Telegram',
    export: 'Экспорт',
    settings: 'Настройки',
    nav: 'Разделы',
  },
  menu: 'Меню',
  filters: 'Фильтры',
  resetFilters: 'Сбросить фильтры',
  searchConfigs: 'Поиск конфигов',
  searchConfigsPlaceholder: 'Страна, адрес, соединение',
  searchProxies: 'Поиск прокси',
  searchProxiesPlaceholder: 'Адрес или страна',
  select: 'Выбрать',
  doneSelecting: 'Закончить выбор',
  liveParse: 'Живой парс',
  showUnverified: 'Показать непроверенные',
  showUnstable: 'Показать нестабильные',
  selectShown: 'Выбрать показанные',
  selected: (count: number) => `Выбрано ${count}`,
  clear: 'Снять',
  text: 'Текст',
  encoded: 'Код',
  encodedCopied: 'Код скопирован',
  file: 'Файл',
  qr: 'QR-код',
  qrShort: 'QR',
  qrBuilding: 'Строим QR…',
  qrFailed: 'Не удалось построить QR',
  qrLong: 'Ссылка длинная, код получится плотным. Надёжнее скопировать её текстом.',
  qrHint: 'Код чёрный на белом, чтобы его можно было сканировать. Сайт не поднимает туннель.',
  qrTooLong: 'Для QR выберите короткую подборку. Длинный список скачивается файлом.',
  copiedCount: (count: number) => `Скопировано: ${count}`,
  picture: 'Картинка',
  share: 'Поделиться',
  copy: 'Копировать',
  details: 'Подробности',
  choose: (title: string) => `Выбрать ${title}`,
  qrOf: (title: string) => `QR-код ${title}`,
  detailsOf: (title: string) => `Подробности ${title}`,
  copyOf: (title: string) => `Скопировать ${title}`,
  openIn: (name: string) => `Открыть в ${name}`,
  clientFallback: 'клиенте',
  openInTelegram: (title: string) => `Открыть ${title} в Telegram`,
  copyHttps: 'Скопировать ссылку',
  httpsCopied: 'Ссылка скопирована',
  qrProxy: 'QR прокси',
  inTelegram: 'В Telegram',
  bestInTelegram: (place: string, ping: string) => `Лучший в Telegram · ${place} · ${ping}`,
  country: 'Страна',
  allCountries: 'Все страны',
  all: 'Все',
  kinds: { all: 'Все', mtproto: 'MTProto', socks: 'SOCKS' },
  view: 'Вид',
  sort: 'Сортировка',
  ping: 'Пинг',
  protocol: 'Протокол',
  connection: 'Тип соединения',
  security: 'Защита',
  countriesByCount: 'Страны по числу',
  countriesByPing: 'Страны по пингу',
  noCountry: 'Без страны',
  portOpen: 'только открытый порт',
  noun: {
    config: ['конфиг', 'конфига', 'конфигов'] as const,
    country: ['страна', 'страны', 'стран'] as const,
  },
  fields: {
    address: 'Адрес',
    port: 'Порт',
    connection: 'Тип соединения',
    security: 'Защита',
    serverName: 'Имя сервера',
    flow: 'Поток',
    path: 'Путь',
    headerName: 'Имя в заголовке',
    service: 'Имя службы',
    tlsPrint: 'Отпечаток TLS',
    id: 'Идентификатор',
    name: 'Название',
    ipCountry: 'Страна IP',
    countryMark: 'Метка страны',
    fromName: 'Флаг в названии',
    fromAddress: 'По адресу сервера',
    stability: 'Стабильность',
    speed: 'Скорость',
    handshake: 'Подключение',
    status: 'Статус',
    list: 'Список',
    checked: 'Проверено',
    publicKey: 'Ключ Reality',
    shortId: 'Короткий код',
    fingerprint: 'Отпечаток',
  },
  copyConfig: 'Ссылка конфига скопирована',
  copyLink: 'Скопировать ссылку',
  linkOnly: 'Только ссылка',
  slices: 'Срезы',
  protocols: 'Протоколы',
  countries: 'Страны',
  securityAndConnection: 'Защита и соединение',
  allVerified: 'Все проверенные',
  withUnstable: 'Вместе с нестабильными',
  top: (count: number) => `Топ ${count}`,
  linkForClientOnly: 'Для этого клиента есть только ссылка',
  subscriptionCopied: 'Ссылка скопирована',
  buildSubscription: 'Собрать подписку',
  inListNow: (count: number) => `В списке сейчас: ${count}`,
  copySelection: 'Ссылка подборки скопирована',
  selection: 'Подборка',
  downloadCount: (count: number) => `Скачать ${count}`,
  any: 'все',
  copySubscription: 'Ссылка подписки скопирована',
  copySubscriptionUrl: 'Скопировать ссылку',
  copyEncodedUrl: 'Скопировать ссылку на код',
  encodedUrlCopied: 'Ссылка на код скопирована',
  copyAllLinks: 'Скопировать все ссылки',
  copiedConfigs: (count: number) => `Скопировано конфигов: ${count}`,
  subscriptionQr: 'QR подписки',
  allSubscriptions: 'Все подписки',
  settings: {
    client: 'Клиент',
    app: 'Приложение',
    siteAddress: 'Адрес сайта',
    info: 'Информация',
    version: (version: string) => `Версия: ${version}`,
    check: (value: string) => `Проверка: ${value}`,
    lastRun: (value: string) => `Последний запуск: ${value}`,
    pingMeaning: 'Пинг — время ответа сайта, без времени подключения',
    inList: (published: number, tested: number) => `В списке: ${published} прокси из ${tested} проверок`,
    inListEmpty: 'В списке: —',
    countryLine: (countries: number, median: string) => `Стран: ${countries} · средний пинг ${median}`,
    countryEmpty: 'Стран: —',
    rejected: (parts: string) => `Отброшено: ${parts}`,
    guide: 'Инструкции',
    sources: 'Источники',
    sourceError: 'ошибка',
    lowYield: 'низкий выход',
    about: 'Об авторе',
    aboutText: 'Самоучка: Rust, фронтенд, бэкенд, Python, AI, навыки для агентов, промпты.',
    github: 'GitHub',
    repo: 'Репозиторий',
    versionShort: (version: string) => `Версия ${version}`,
    updated: (stamp: string) => `обновлено ${stamp}`,
    save: 'Сохранить',
    restoreAddress: 'Вернуть обычный адрес',
    dash: '—',
  },
  guide: {
    intro:
      'V2Hub собирает публичные конфиги и прокси Telegram, проверяет их и отдаёт списками. Сайт не поднимает туннель и не подключается к серверу за вас.',
    readTitle: 'Как читать результат',
    read: 'Точка на строке — рабочий или нестабильный конфиг. Пинг — время ответа сайта после подключения. Рядом доля успешных проверок и скорость. «Только открытый порт» значит, что сервер ответил, а полный проход в этом запуске не выполнялся.',
    takeTitle: 'Как забрать конфиги',
    take: '«Экспорт» — готовые списки по стране, защите и типу соединения, а также файлы для Clash и sing-box. На «Конфигах» отметьте строки и выгрузите текст, код, файл, QR или файл для приложения.',
    checkTitle: 'Проверка',
    check:
      'Сначала ссылка разбирается, затем проверяется, открыт ли порт, проходит ли подключение и открывается ли сайт. Рабочий держится хотя бы в 70% последних проверок. Нестабильный прошёл сейчас, но реже. Нерабочий в список не попадает. Проверка идёт с серверов GitHub вне России, поэтому домашний провайдер может закрыть то, что здесь открылось.',
    telegramTitle: 'Telegram',
    telegram: 'Кнопка «В Telegram» открывает приложение и подставляет прокси. Если оно не открылось, рядом есть ссылка и QR.',
    inspectTitle: 'Разбор ссылки',
  },
  inspect: {
    title: 'Разбор ссылки',
    hint: 'Ссылка разбирается в браузере. Плюс в ключе остаётся плюсом, название в отпечаток не входит.',
    placeholder: 'vless://…',
    aria: 'Ссылка VLESS',
    notVless: 'Это не ссылка VLESS',
    run: 'Разобрать',
    qrClients: 'QR и приложения',
  },
  live: {
    title: 'Живой парс',
    find: 'Найти новые',
    reading: 'Читаем источники…',
    progress: (done: number, total: number, parsed: number, fresh: number, skipped: number) =>
      `Источники ${done}/${total} · разобрано ${parsed} · новых ${fresh} · пропущено ${skipped}`,
    browser: 'Браузер не проверяет конфиги.',
    startCheck: 'Запустить проверку',
    refreshList: 'Обновить список',
    copyNew: 'Скопировать новые',
    newCopied: 'Новые ссылки скопированы',
    download: 'Скачать',
    unchecked: 'не проверены',
    first: (shown: number, total: number) => `В списке первые ${shown}, в файле все ${total}.`,
    queued: 'Проверка в очереди',
    running: 'Проверка идёт',
    done: 'Проверка завершилась',
    failed: 'Проверка остановилась с ошибкой',
    cancelled: 'Проверка отменена',
    rateLimit: 'Слишком много запросов, статус позже',
    unknown: 'Статус проверки неизвестен',
    onGithub: 'Проверка на GitHub',
    skipTelegram: 'страница Telegram',
  },
  reasons,
  statuses,
  probes,
  otherError: 'Другая ошибка',
  noStatus: 'Без статуса',
  probeFallback: 'Проверка с сервера',
} as const

export function reasonLabel(key: string): string {
  const label = (reasons as Record<string, string>)[key]
  if (!label) return ru.otherError
  return label
}

export function statusLabel(status: string | null | undefined): string {
  if (!status) return ''
  const label = (statuses as Record<string, string>)[status]
  return label ?? ru.noStatus
}

export function probeLabel(probe: string | null | undefined): string {
  if (!probe) return ru.settings.dash
  const label = (probes as Record<string, string>)[probe]
  return label ?? ru.probeFallback
}

export function kindLabel(kind: string): string {
  if (kind === 'mtproto') return ru.kinds.mtproto
  if (kind === 'socks') return ru.kinds.socks
  return ru.kinds.all
}
